<a href="https://colab.research.google.com/github/Jassii/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Study about NumPy

It is used to do typical numerical calculation on multidimensional arrays along with some other sophisticated functions. It provides ease working with linear algebra and carrying out complex calculations like Matrix inversion, Fourier transforms, etc...

In [10]:
import numpy as np

Example 1

In [11]:
lst = [1,2,3,4,5]  

In [14]:
arr = np.array(lst)  #converting the list into array..


In [15]:
print(arr+5)  #print the array after increasing each value by 5..

[ 6  7  8  9 10]


Example 2

In [16]:
lst = [1, 2, 3, 'text', True, 3+2j] 
arr = np.array(lst)
#now it's time to check the homogenity(numpy array works the similar data type..)

In [17]:
print(type(arr[0]),type(arr[4]),type(arr[5]))   #it is returning the type of the specified element of (class) as (numpy.str)

<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>


Example 3

In [21]:
lst = [56, 45, 12, 6]
arr = np.array(lst)
#we have to calculate the number of bytes occupied by this list 

In [22]:
print(arr.nbytes)

32


**Numpy Object Creation**

In [23]:
#create an array using numpy
arr = np.array([1,2,3,4,5], dtype=int)  #dtype tells about the data type..

In [24]:
arr

array([1, 2, 3, 4, 5])

In [25]:
type(arr)

numpy.ndarray

In [28]:
np.result_type(arr)   #inorder to check the type of the elements present in the array..

dtype('int64')

Here, we have used np.array() function which takes 2 arguments, the input list, and the corresponding data type (dtype). To check the data type of a particular NumPy object we have used np.result_type() command.

**NumPy offers some frequently used functions to create a NumPy object as shown below:**

In [36]:
arr = np.arange(0,10,1.33, dtype=np.float64)  #1.33 will be considered as the steps between the values..
print(arr)  #printing the elements present in the array..
# arange() gives uncertain number of values based on steps

# Hence, we use linspace, which asks for total number of values 
arr = np.linspace(0,160,5, dtype=np.float64) #here 5 is considered as the number of elements in the array
print(arr)

[0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]
[  0.  40.  80. 120. 160.]


**Matrix Creation**

Method 1

In [45]:
#Converting the array into matrix using numpy function..
lst = [1,2,3,4,5,6]
arr = np.array(lst)   #converting the list into array..
print(arr.reshape(2,3))  #now converting the array into matrix representation..

[[1 2 3]
 [4 5 6]]


Method 2 - Using matrix inbuilt function

In [51]:
print(  np.matrix(  [       [1,2,3],[4,5,6],[7,8,9]   ]  )  ) #list is passed inside the list..

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Method 3 - Using misc function

In [52]:
print(np.eye(3))  #only diagnol function is 1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
print(np.zeros(   (4,3) ) )  #zero matrix..

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [56]:
print(np.ones((2,2)))  #identity function..

[[1. 1.]
 [1. 1.]]


Question

In [64]:
arr1 = np.array([25, 56, 12, 85, 34, 75], dtype=np.int64)
arr2 = np.array([42, 3, 86, 32, 856, 46], dtype=np.int64)
print(arr1)
print(arr2)

[25 56 12 85 34 75]
[ 42   3  86  32 856  46]


**The numpy.random.rand() function creates an array of specified shape and fills it with random values.**

In [77]:
Narr = np.random.rand(6)  #the array will store random values of the size mentioned..
Narr

array([0.20198562, 0.65990163, 0.74243154, 0.82597156, 0.94213045,
       0.73048859])

**In order to change the dtype of the given array object, we will use numpy.astype() function.**

Permanently change the dtype of arr1 to complex.

In [82]:
arr1 = arr1.astype(np.complex64)
print(arr1)

[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]


In [70]:
arr1_mat = arr1.reshape(2,3)

In [71]:
arr2_mat = arr2.reshape(2,3)

In [73]:
print(arr1_mat,"\n",arr2_mat)

[[25.+0.j 56.+0.j 12.+0.j]
 [85.+0.j 34.+0.j 75.+0.j]] 
 [[ 42   3  86]
 [ 32 856  46]]
