<a href="https://colab.research.google.com/github/Jassii/Numpy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Study about NumPy

It is used to do typical numerical calculation on multidimensional arrays along with some other sophisticated functions. It provides ease working with linear algebra and carrying out complex calculations like Matrix inversion, Fourier transforms, etc...

In [2]:
import numpy as np

Example 1

In [3]:
lst = [1,2,3,4,5]  

In [4]:
arr = np.array(lst)  #converting the list into array..


In [5]:
print(arr+5)  #print the array after increasing each value by 5..

[ 6  7  8  9 10]


Example 2

In [6]:
lst = [1, 2, 3, 'text', True, 3+2j] 
arr = np.array(lst)
#now it's time to check the homogenity(numpy array works the similar data type..)

In [7]:
arr[0]  #it is returning the value in the form of string...(using np...it will store the value in the form of string)..

'1'

In [8]:
print(type(arr[0]),type(arr[4]),type(arr[5]))   #it is returning the type of the specified element of (class) as (numpy.str)

<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>


Example 3

In [9]:
lst = [56, 45, 12, 6]
arr = np.array(lst)
#we have to calculate the number of bytes occupied by this list 

In [ ]:
print(arr.nbytes) #use of nbytes..

32


**Numpy Object Creation**

In [10]:
#create an array using numpy
arr = np.array([1,2,3,4,5], dtype=int)  #dtype tells about the data type..

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
np.result_type(arr)   #inorder to check the type of the elements present in the array..

dtype('int64')

Here, we have used np.array() function which takes 2 arguments, the input list, and the corresponding data type (dtype). To check the data type of a particular NumPy object we have used np.result_type() command.

**NumPy offers some frequently used functions to create a NumPy object as shown below:**

In [ ]:
arr = np.arange(0,10,1.33, dtype=np.float64)  #1.33 will be considered as the steps between the values..
print(arr)  #printing the elements present in the array..
# arange() gives uncertain number of values based on steps

# Hence, we use linspace, which asks for total number of values 
arr = np.linspace(0,160,5, dtype=np.float64) #here 5 is considered as the number of elements in the array
print(arr)

[0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]
[  0.  40.  80. 120. 160.]


**Matrix Creation**

Method 1

In [ ]:
#Converting the array into matrix using numpy function..
lst = [1,2,3,4,5,6]
arr = np.array(lst)   #converting the list into array..
print(arr.reshape(2,3))  #now converting the array into matrix representation..

[[1 2 3]
 [4 5 6]]


Method 2 - Using matrix inbuilt function

In [ ]:
print(  np.matrix(  [       [1,2,3],[4,5,6],[7,8,9]   ]  )  ) #list is passed inside the list..

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Method 3 - Using misc function

In [ ]:
print(np.eye(3))  #only diagnol function is 1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.zeros(   (4,3) ) )  #zero matrix..

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones((2,2)))  #identity function..

[[1. 1.]
 [1. 1.]]


Question

In [ ]:
arr1 = np.array([25, 56, 12, 85, 34, 75], dtype=np.int64)
arr2 = np.array([42, 3, 86, 32, 856, 46], dtype=np.int64)
print(arr1)
print(arr2)

[25 56 12 85 34 75]
[ 42   3  86  32 856  46]


**The numpy.random.rand() function creates an array of specified shape and fills it with random values.**

In [ ]:
Narr = np.random.rand(6)  #the array will store random values of the size mentioned..
Narr

array([0.20198562, 0.65990163, 0.74243154, 0.82597156, 0.94213045,
       0.73048859])

**In order to change the dtype of the given array object, we will use numpy.astype() function.**

Permanently change the dtype of arr1 to complex.

In [ ]:
arr1 = arr1.astype(np.complex64)  #astype() function is used in order to change the data type permanently..
print(arr1)

[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]


In [ ]:
arr1_mat = arr1.reshape(2,3)

In [ ]:
arr2_mat = arr2.reshape(2,3)

In [ ]:
print(arr1_mat,"\n",arr2_mat)

[[25.+0.j 56.+0.j 12.+0.j]
 [85.+0.j 34.+0.j 75.+0.j]] 
 [[ 42   3  86]
 [ 32 856  46]]


In [15]:
arr = np.ones(10) #1D array...

In [16]:
type(arr)  #it returns the type of array..

numpy.ndarray

In [17]:
np.result_type(arr)  #returns the type of the elements present

dtype('float64')

In [18]:
arr2 = np.arange(10, dtype = np.float64)

In [19]:
np.result_type(arr2)

dtype('float64')

**Vectorized operations**

Example 1

In [20]:
S_X = np.array([[2, 5, 6, 5],  
               [4, 8, 6, 5]])  #defining 2D array..
print(S_X)

S_Y = np.array([[6, 7, 5, 9],
               [7, 5, 6, 4]])  #defining 2D array..
print(S_Y)

[[2 5 6 5]
 [4 8 6 5]]
[[6 7 5 9]
 [7 5 6 4]]


**1. Quarterly difference between each state's literacy rate per year**

In [21]:
print(S_Y - S_X)  #we will subtract both the arrays.

[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


**2. Quarters having a literacy rate less than 2.**

In [23]:
print((S_Y)<2)  #For Case Y

[[False False False False]
 [False False False False]]


In [24]:
print((S_X)<2) #For Case X

[[False False False False]
 [False False False False]]


Some Examples


In [51]:
#Given a matrix mat, sort it by the second column.
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])
out = np.argsort(mat)  #it returns the array of indices that would sort the array...
print(mat[out])                                                                          #not so much clear.

[[[ 1 21  3]
  [56 12  4]
  [ 5  4  2]]

 [[56 12  4]
  [ 5  4  2]
  [ 1 21  3]]

 [[56 12  4]
  [ 5  4  2]
  [ 1 21  3]]]


In [63]:
#Given an array arr, find the top 4 maximum values.
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])
print(arr)
arr = arr[arr.argsort()]  #using argsort() inorder to sort the array..
print(arr)
print(arr[-4:])

   #top 4 maximum vales..

[ 90  14  24  13  13 590   0  45  16  50]
[  0  13  13  14  16  24  45  50  90 590]
[ 45  50  90 590]


**6. Find the nearest number from the given number in an array.**

In [64]:
arr = np.array([10,55,22,3,6,44,9,54])
print(np.argmin(arr))                 #not clear...

3


**Additional operations**

**3. Quarters having a literacy rate with cumulative sum of more than or equal to 8 per year.**

In [70]:
S_X

array([[2, 5, 6, 5],
       [4, 8, 6, 5]])

In [68]:
X_cumsum = np.cumsum(S_X, axis = 1)  #numpy.cumsum() function is used when we want to compute the 
#cumulative sum of array elements over a given axis.                         #axis =1 means column..

In [71]:
print(X_cumsum)

[[ 2  7 13 18]
 [ 4 12 18 23]]


In [72]:
print(X_cumsum>8)

[[False False  True  True]
 [False  True  True  True]]


In [73]:
Y_cumsum = np.cumsum(S_Y,axis=1)
print(Y_cumsum)

[[ 6 13 18 27]
 [ 7 12 18 22]]


In [74]:
print(Y_cumsum>8)

[[False  True  True  True]
 [False  True  True  True]]


**4. Mean of each year's literacy rate of State X and mean of each quarterly's literacy rate of State Y.**

numpy.mean(arr, axis = None) : Compute the arithmetic mean (average) of the given data (array elements) along the specified axis.

In [75]:
print(np.mean(S_X,axis=1))

[4.5  5.75]


In [76]:
print(np.mean(S_Y,axis=1))

[6.75 5.5 ]
